version: '3.8'

services:
  api-gateway:
    build: 
      context: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    networks:
      - microservices-network
    depends_on:
      - login-service
      - chess-service
      - chat-service

  login-service:
    build:
      context: ./backend/login-service
    container_name: login-service
    ports:
      - "3001:3001"
    networks:
      - microservices-network
    depends_on:
      - mysql

  chess-service:
    build:
      context: ./backend/chess-service
    container_name: chess-service
    ports:
      - "3002:3002"
    networks:
      - microservices-network
    depends_on:
      - mongo-chess

  chat-service:
    build:
      context: ./backend/chat-service
    container_name: chat-service
    ports:
      - "3003:3003"
    networks:
      - microservices-network
    depends_on:
      - mongo-chat

  mysql:
    image: mysql:8
    container_name: mysql-login
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservices-network

  mongo-chat:
    image: mongo:6
    container_name: mongo-chat
    ports:
      - "27017:27017"
    volumes:
      - mongo_chat_data:/data/db
    networks:
      - microservices-network

  mongo-chess:
    image: mongo:6
    container_name: mongo-chess
    ports:
      - "27018:27017"
    volumes:
      - mongo_chess_data:/data/db
    networks:
      - microservices-network

volumes:
  mysql_data:
  mongo_chat_data:
  mongo_chess_data:

networks:
  microservices-network:
    driver: bridge